### PR TITLE
upgraded all dependecies

### LINKED ISSUE #7: dependency problem
regarding my flutter/dart-project I receive the follwong error:

Because what3words >=3.1.0 depends on chopper ^4.0.1 which depends on http >=0.13.0 <1.0.0, what3words >=3.1.0 requires http >=0.13.0 <1.0.0.
So, because gc_wizard depends on both http ^1.1.0 and what3words ^3.1.0, version solving failed.

When downgrading the http-lib to <1.0.0 I get another dependeny conflict.
On the other hand, the current version of chopper is 7.0.6 which depends on http 1.1.0.

So updating the w3w-wrapper to uses chopper 7.o.6 would solve this conflict.
Hence I recommend to update pubspec.yaml and adjust the source files

### PR DESCRIPTION
**Pull request by sonigeez**
fix #7

### CODE REVIEW

**Comment by chrispage1** [comment]
I've just come across this issue now. Such a shame it doesn't seem to be actively maintained at the minute.

**Comment by sonigeez** [comment]
@ManuCiao please let us know if we can help in maintaining the dart library, w3w is a great project and we all love it, would love to get more support from team.

**Comment by ManuCiao** [comment]
I am looking into it this week and let you know when we can release a new library asap. @sonigeez

**Comment by ManuCiao** [comment]
@sonigeez @chrispage1 I created a new release and bumped the version of the wrapper to 3.2.0 please check it out and let me know. I couldn't use your pull request because some other dependencies and updates needed to occur.
Are you happy for me to close this pull request and check out our new update?  many thanks.

**Comment by chrispage1** [comment]
Thanks @ManuCiao !

**Pull request closed without merging**
